### ISSUE TITLE
Editor does not draw the drawings.

### ISSUE THREAD

**Issue by V205Arduino** [hackclub/blot#105]
The Editor does not draw the drawings.
https://haxidraw.hackclub.dev/editor
I press run but it does not run.

**Comment by V205Arduino** [comment]
Also tried shift return

**Comment by leomcelroy** [comment]
Can you send an example?

**Comment by V205Arduino** [comment]
Ok will do! Please wait....

**Comment by V205Arduino** [comment]
Can't even access the website. It now returns a 404 error.....

**Comment by V205Arduino** [comment]
Update: The link https://blot.hackclub.dev/editor
works. Will test. Please wait...

**Comment by V205Arduino** [comment]
Yay!!!!!!!!!!!!! The editor now works. 
More info:
Fail on:
IpadOS
Browser: Safari

Works on 
MacOS
Browser:
Safari and Chrome

Thank you!!!
