### ISSUE TITLE
Rewrite README and upload KiCAD files /whatnot 

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/blot#108]
The circuit part for blot repo is outdated. will update with:
- newest carrier board 
- fixed 9V1A cypd3177 board
- iamges! 

KiCAD v7 sch, brd, schematic capture, BOM, PCB layout

**Comment by Sheepy3** [comment]
could we get .svg's of the boards too?

**Comment by Hugoyhu** [comment]
Yes, but not sure if those will look nice. I'll be happy to draw mechanical size charts
@Sheepy3 could you please DM me on this for what SVGs for etc. CLosing this issue for now
