### ISSUE TITLE
Make generative art!!! 🌈

### ISSUE THREAD

**Issue by exu3** [hackclub/blot#11]
Ways you can contribute by making generative art:

- **Make a parametric art generator.** [Drawingbots](https://drawingbots.net/) is a good resource. Specifically the [tool section](https://drawingbots.net/knowledge/tools) has a bunch of examples of parametric line art generators that produce plottable patterns.
- **Make some parametric art.** Make some generative art which could be drawn by a plotter. For some examples of this check out  some these blogs:
	- https://revdancatt.com/
	- https://penplotterartwork.com/
	- https://greweb.me/
	- https://targz.fr/
	- https://larswander.com/
	- https://www.v3ga.net/
	- https://bylr.info/
	- http://andymakes.com/#Plotter
	- https://www.eyesofpanda.com/
	- https://mattdesl.svbtle.com/pen-plotter-1
	- https://muffinman.io/art/

Host your code somewhere where it's publicly accessible, like GitHub, and post what you make in the `#ship` and `#development-of-stuff-and-things` channels on the [Hack Club Slack](https://hackclub.com/slack)!

**Comment by cytronicoder** [comment]
This would be really cool to work on! Let me see if I can spend some time on an editor haha
