### ISSUE TITLE
Make "paper" lines smooth

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/blot#115]
![Screenshot 2023-09-19 at 3 44 16 PM](https://github.com/hackclub/blot/assets/27078897/9a40ad95-6beb-4ade-a779-c47db4cb96d0)

**Comment by jianmin-chen** [comment]
Okay background image also doesn't work for this, so I assume it's a Chrome transform thing

**Comment by Sheepy3** [comment]
no longer used
