### ISSUE TITLE
Take glamour shots of machine

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/blot#122]
- make some gifs of it running

**Comment by karamassie** [comment]
@Hugoyhu is also a fab photographer....

**Comment by Sheepy3** [comment]
mailed him parts for a new machine last week, he could take some good pictures once it arrives. Though the quality of the prints of his machine may not perfectly represent the final product, I was still tweaking the printer's settings.

**Comment by Hugoyhu** [comment]
I will do a photoshoot of blotty bot + related PCBs with my setup when I get my fab sunset orange PLA parts installed. Will keep you updated via slack and assigning myself to issue

**Comment by leomcelroy** [comment]
Couple of specific shots we want

- a video of the machine running
  - drawing leaf, squiral, something nice
  - use a thick pen
  - do a couple takes at different angles
  - need to be able to remove background
- a shot of all the parts
- a shot of each part individually

**Comment by Sheepy3** [comment]
finished shots of each part individually, finished shots of PCB

**Comment by Sheepy3** [comment]
took shots of machine, were not high quality enough, will take shots again at next available time

**Comment by Sheepy3** [comment]
scheduled time next week to take more photos.
