### ISSUE TITLE
inconsistent camelcase

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/blot#131]
multi word functions like setAngle use camelcasing, but goto does not. should be goTo?

**Comment by VivekChatterjee** [comment]
Yes, it should be good to have uniform camel casing everywhere.

**Comment by leomcelroy** [comment]
It's funny because it's actually switched back and forth. Alright let's go with `goTo`.

We'll have to update the gallery and workshops

**Comment by JCardona0110** [comment]
hello! i can take care of this issue

**Comment by V205Arduino** [comment]
Hmm. Could it be made to be backwards compatible?
I have some code that uses goto,.....

**Comment by recursiveforte** [comment]
now that I think of it… what if blot functions weren’t case-sensitive?

**Comment by V205Arduino** [comment]
Should be following camel case. 
What does sprig use?

**Comment by leomcelroy** [comment]
Just update your code @V205Arduino
