### ISSUE TITLE
imported SVG's are flipped

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/blot#137]
Intended result:
![image](https://github.com/hackclub/blot/assets/109123711/b4e9caa4-1bbd-4f61-9494-e598c61bb6c9)

Actual result: 
![image](https://github.com/hackclub/blot/assets/109123711/55105c24-ca7f-4e56-8315-d4672b7ad442)

**Comment by leomcelroy** [comment]
The editor space is flipped in y. I added an extra line on import to flip the dropped in svg in code.
