### ISSUE TITLE
test carriage warping

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/blot#152]
reported issues of carriage warping. testing warping on a 40% infill 4-perimeter PETG carriage, by placing it under stress for an extended period of time.

**Comment by Sheepy3** [comment]
will be receiving aluminum plate soon, will likely result in minimization of warping. as for current test running, not seeing any issues so far, but it has only been 2 weeks. we will most likely release the first run of blot's with the aluminum plate, and if we find that the newer designed parts do not suffer from warping, we can just stop giving people them.

**Comment by leomcelroy** [comment]
This plan sounds good shawn. Going to close this for now. I'm happy with the plate I've used so far. Let's keep a design for the not plate version of the carriage so people can print machines if they want.
