### ISSUE TITLE
After loading a file, blot draws previous content

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#160]
![IMG_0482](https://github.com/hackclub/blot/assets/5891442/a880ff3f-0064-4205-a8fb-4f7a1dc22b21)

Steps I took to replicate:

- Opened the editor
- Opened the "square-disarray" drawing
- Ran the machine
- Clicked "load file"
- Loaded a new drawing
- Ran the machine

Expected result: it draws the newly loaded drawing that shows up in the renderer
Actual result: it draws the "square-disarray" drawing

**Comment by leomcelroy** [comment]
I can't replicate this now after some firmware updates so will consider addressed.
