### ISSUE TITLE
Difference between editor preview and blot drawing when using Math.random()

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#161]
<img width="435" alt="Screenshot 2023-11-15 at 12 10 52" src="https://github.com/hackclub/blot/assets/5891442/3a4a4d4a-3eb8-4446-a12a-449e8ea7d746">

- It wasn't clear to me that I had to use `rand()` to prevent this because I hadn't scrolled to that part of the docs. 
- I didn't realize I was using `Math.random()` because I copied code from an example implementation of a K-mean algorithm online

I'd propose fixing by prototyping `Math.random()` to give a warning on first usage. That'd help...
- warn people who don't know they need to use `rand()`, 
- people who accidentally used `Math.random()` even though they know to use `rand()`

**Comment by BrightTheBackpack** [comment]
if someone implements a warning system for different functions, can you also add a warning for print()? I once had a 100 long for loop and had to close the print page prompt 100 times.

**Comment by maxwofford** [comment]
@BrightTheBackpack Want to create a new ticket for that? I think that's a separate discussion because `Math.random()` is something that we're treating different on our site. Things like `print()` `alert()` and `prompt()` can be prototyped, but that's more browser specific, not site specific.

**Comment by maxwofford** [comment]
Just tested this and it's no longer erroring on submissions like this: https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/hackclub/blot/main/art/BeautifulSaturn-AlexB/index.js
