### ISSUE TITLE
Unclear how to (0,0) the machine

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#162]
When starting the machine and connecting I had trouble figuring out how to set the zero position of the machine. At first I tried setting it to the 4 corners, but each time when drawing a box it ended up making a grinding sound. I eventually started the machine in the very center and just making tiny drawings.

<img width="429" alt="Screenshot 2023-11-15 at 12 18 15" src="https://github.com/hackclub/blot/assets/5891442/69c936f1-d10c-4ae7-bac5-dcda5e0ec9fe">

After getting instructions to disconnect the machine to zero it I thought I could click the "disconnect machine" button, but found that it didn't zero the machine like I expected it to.

**Comment by BrightTheBackpack** [comment]
zeroing machine was added to the tuning guide!

**Comment by maxwofford** [comment]
Closed by https://github.com/hackclub/blot/blob/main/docs/TUNING.md#using-your-blot
