### ISSUE TITLE
Unclear if machine is running

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#163]
<img width="424" alt="Screenshot 2023-11-15 at 12 19 49" src="https://github.com/hackclub/blot/assets/5891442/5d336042-b778-460d-886b-26b81bd37ade">

The editor UI has a button to "Run machine", but doesn't have a way to tell if I've clicked it. After clicking and the machine not responding I can't tell if...

- I didn't click the button
- My script hit an error that didn't throw
- My script runs long and is still processing
- My script has an infinite loop
- There's a problem with the physical connection to the machine, or from the control board to the motors

**Comment by leomcelroy** [comment]
It changes state now. Could show a progress bar to be improved more.
