### ISSUE TITLE
"Run machine" regenerates art with a new seed

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#164]
<img width="457" alt="Screenshot 2023-11-15 at 12 23 08" src="https://github.com/hackclub/blot/assets/5891442/d6d93ef0-0ee3-4cba-ac67-e8b1d2b29ae8">

**Comment by Sheepy3** [comment]
perhaps a way to see the seed that the current drawing is using and subsequently lock it in place?

**Comment by leomcelroy** [comment]
I made it not re-run the piece.
