### ISSUE TITLE
"Run" button isn't debounced

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#165]
Steps to replicate:

- Create a long running script with lots of nested loops
- Click "run"
- [See no indication it's running, so click "run" multiple more times](https://github.com/hackclub/blot/issues/163)

Expected behavior:
- It generates either the most recent "run", cancelling previous artwork in progress _OR_
- It ignores new button presses until the original art finishes generating

Actual behavior:
- It runs over and over without a way to cancel, eventually freezing the tab

**Comment by maxwofford** [comment]
Ah, to clarify this issue, I'm hitting the "shift+enter Run" button that generates art, not runs the machine. I have some art with a lot of recursion that ends up freezing the tab.

**Comment by leomcelroy** [comment]
I see. It's not really possible to halt the process without the difficulties that come from running it in a web worker. You can reopen this but I'm not sure we'll address it soon.

**Comment by maxwofford** [comment]
If this is a "closed as won't fix" I think that's fine! Just getting this documented as a known "thing" is probably fine for now.

**Comment by leomcelroy** [comment]
This is addressed by moving evaluation to a web worker which will be merged to main shortly.

**Comment by maxwofford** [comment]
Are we closing this as fixed or as won't fix?

**Comment by leomcelroy** [comment]
Addressed with #341
