### ISSUE TITLE
Strange result after rotating art

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#166]
[This art](https://cloud-32z40dwz3-hack-club-bot.vercel.app/0slanted.js) looks different in the previewed version and the actual drawn version. The squares turned out slanted.

![IMG_0485](https://github.com/hackclub/blot/assets/5891442/b750d4c3-a3e7-45e9-8d58-b0c02cd4454a)

![Screenshot 2023-11-14 at 19 47 38](https://github.com/hackclub/blot/assets/5891442/3bcf0924-4e82-492b-a374-9c0d13533e00)

**Comment by leomcelroy** [comment]
I think this has to do with how the machine was physically assembled. It looks alright on my machine. Corners could be sharper but not this egregious.

**Comment by maxwofford** [comment]
@leomcelroy if this is a hardware issue with the machine, maybe the solution is a "my blot won't draw straight, what's next" document to help people troubleshoot their machine. Should we create a new ticket for that or re-open this with an updated title?

**Comment by leomcelroy** [comment]
Let's make a new ticket for the tuning guide you recomended.
