### ISSUE TITLE
Unexpected behavior when trying to share a piece

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#167]
I tried to send someone a link to a piece of art found in the gallery, but the link didn't work. Steps to replicate:

- Go to the gallery:
<img width="757" alt="Screenshot 2023-11-15 at 12 32 21" src="https://github.com/hackclub/blot/assets/5891442/d732acd7-1c1f-40be-b42b-432102bc9f5d">
- Click on a piece
- Copy the URL of the piece in the editor

Expected behavior:
- The link I'm taken to can be shared with others
- The art I've been working on isn't overwritten
Actual behavior:
- I get the generic editor link that shows different content on someone else's computer
- My previous work has been overwritten

**Comment by jianmin-chen** [comment]
Just flagging - this should work after PR #177 is merged.

**Comment by leomcelroy** [comment]
#341 adds a share link button.
