### ISSUE TITLE
add what is vim mode

### ISSUE THREAD

**Issue by LucasHT22** [hackclub/blot#171]
I didn't find anywhere what vim mode is
![image](https://github.com/hackclub/blot/assets/88567622/681441b9-951b-43d1-9231-98cb35b035c0)

**Comment by Sheepy3** [comment]
https://www.vim.org/ its to enable vim-style keybindings, to my understanding. only really useful if you already know what vim is!

**Comment by LucasHT22** [comment]
oh this vim, nice
