### ISSUE TITLE
doing print() causes page print to occur when running

### ISSUE THREAD

**Issue by BrightTheBackpack** [hackclub/blot#179]
Some people(like me) who are ultra familiar with python syntax may accedently do print() instead of console.log(). This results in the page print prompt to show up on chrome(haven't tested on any other browsers) when running.
```[tasklist]
### Tasks
```

**Comment by kalpan-shah** [comment]
Hi @BrightTheBackpack  ,I'll say you will face that in any browser,( except your regular node native without browser) cause the JS print() invokes the printer utility in windows. so console.log() is the only way my friend you'll be able to make a simple print() just like python.

I know it's hard to switch the familiarity.

**Comment by BrightTheBackpack** [comment]
I feel like there should be a warning before you click run if you have a print() statement.
