### ISSUE TITLE
Tuning guide

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#183]
_or, "Now I've got my blot, how do I make it draw good?"_

I'm opening this based on [this thread](https://github.com/hackclub/blot/issues/166#issuecomment-1821674631). We probably want a documented guide on how to tune / fix the machine for users.

**Comment by leomcelroy** [comment]
This is a work in progress will close this issue for now for housekeeping.

The current guide is available here: https://github.com/hackclub/blot/blob/main/docs/TUNING.md
