### ISSUE TITLE
Number slider doesn't wait to previous render to finish or cancel current render

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#184]
Related to https://github.com/hackclub/blot/issues/165, I'm able to freeze my tab by making a long-running script, then click+dragging a number value (because it tries to redraw each number change). Is there a way to either only render once the previous image is fully rendered, or cancel previous renders when a new input value is added?

**Comment by maxwofford** [comment]
@leomcelroy was this fixed? Or are we just treating this as something we aren't going to fix?

**Comment by leomcelroy** [comment]
This is addressed by moving evaluation to a web worker and killing out dated runs.

**Comment by maxwofford** [comment]
@leomcelroy have we done that? I don't see a recent commit for that change.
<img width="1294" alt="Screenshot 2024-03-04 at 12 39 31" src="https://github.com/hackclub/blot/assets/5891442/39dabeea-b7d2-403b-b34f-6d1df90eb6c1">

**Comment by maxwofford** [comment]
Mind if we close this once it's in main and we know it's been fixed?

**Comment by leomcelroy** [comment]
Addressed with #341
