### ISSUE TITLE
create shipping process doc

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/blot#186]

**Comment by maxwofford** [comment]
@Sheepy3 What's this for?

**Comment by Sheepy3** [comment]
this issue was for creating a document describing how to pack a blot, which I believe you have been working on

**Comment by leomcelroy** [comment]
I think I used this the other day so will mark this as done.

It's this correct?

https://github.com/hackclub/blot/blob/main/docs/packaging/PACKING.md
