### ISSUE TITLE
Dark mode or customizable pallette

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#194]
Know this seems extravagant, but I find I'm most creative at night and really want to use blot on a dark screen.

I'm 100% ok with not having official support for dark mode; but currently the way the turtle is rendered, extensions like "dark reader" will black out the canvas entirely:

<img width="1427" alt="Screenshot 2023-12-01 at 12 59 39" src="https://github.com/hackclub/blot/assets/5891442/08dcb5be-c508-4e5e-b7d7-6458360588f8">

Short of a full dark-mode, I'd like the ability just to change the color of the pen in the renderer to work with the extension.

**Comment by AverseABFun** [comment]
I also want this feature.
