### ISSUE TITLE
Choose between GH or Vercel as host

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#223]
While investigating why https://github.com/hackclub/blot/pull/210 succeeded its tests and the main branch failed, I realized that https://github.com/hackclub/blot/blob/56f405d58af1d7e9c94fa9ae8492e41011d18db7/.github/workflows/astro.yml deploys to GH pages, but our site is hosted by Vercel's automated deploys. This means we currently have a broken GH CI, but haven't noticed because builds deploy successfully to Vercel.

Should we...
- Stick with Vercel and delete the astro.yml build script? _OR_
- Turn off Vercel autodeploy, fix the astro.yml, and update DNS to point to GH pages?

**Comment by leomcelroy** [comment]
Let's stick with vercel. Can you point me at the astro build script?

**Comment by maxwofford** [comment]
Yeah! Seems like you can just delete [this file](https://github.com/hackclub/blot/blob/main/.github/workflows/astro.yml) and everything should be good to go for vercel's build
