### ISSUE TITLE
Browser asks for refresh everytime you change the code

### ISSUE THREAD

**Issue by ansh3108** [hackclub/blot#229]
When you are working on your blot code, you might have to copy the code every time you modify it because you sometimes have to refresh the page to see the new output!

**Comment by leomcelroy** [comment]
Can you document how to repeat this? I'm not quite sure how to replicate the scenario described.

**Comment by ansh3108** [comment]
If you go to the blot editor and run your code for the first time in the editor and then run it, it works fine. But when you edit the code and then even if you save it, and try to run the code, it doesn't work. You will have to copy the edited code and then refresh the browser to see the new output.

**Comment by V205Arduino** [comment]
what OS? What browser?
I can't replicate this too

**Comment by ansh3108** [comment]
Windows 10 and Brave browser
