### ISSUE TITLE
design improved pen holder compliancy 

### ISSUE THREAD

**Issue by karamassie** [hackclub/blot#24]
some plotters have a way for the user to add pennies for weight. let's try this.

**Comment by karamassie** [comment]
@leomcelroy is this being reassigned?

**Comment by Sheepy3** [comment]
experimented with compliant design, but got dimensions wrong. designed an eccentric-spacer design to be shipped if the compliant design is not finished in time for release

**Comment by Sheepy3** [comment]
designed compliant design, has not been tested extensively. will potentially run tests on it when i have a new board and a spare blot. for now, petg testing is prioritized.
