### ISSUE TITLE
Assembly instructions page isn't mobile friendly

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#242]
![IMG_0746](https://github.com/hackclub/blot/assets/5891442/7106030a-e3a6-4ee9-9304-c0f91785396d)

**Comment by leomcelroy** [comment]
Just made it link to github page instead.

**Comment by maxwofford** [comment]
This was closed by https://github.com/hackclub/blot/commit/544cd861c9d368f133857881e87de1fb335ae1b7

**Comment by maxwofford** [comment]
Swapping this to 'wont fix' to clarify we didn't write any changes to the page.
