### ISSUE TITLE
Tool Head pen-holding screw isn't in the instructions & was packed with an incorrect screw

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#243]
I just went through and built a blot from one of the demo kits in the office.

The tool head has a whole for a screw to hold the pen, but the screw left over from the build looks too long to use and with the wrong size for the allen keys packed in the kit.

![IMG_0745](https://github.com/hackclub/blot/assets/5891442/4f5d56f3-507d-4c32-bef0-d477308bbce5)
![IMG_0744](https://github.com/hackclub/blot/assets/5891442/cd82db1f-8721-432d-9fc4-69785a24fee9)

Additionally there isn't a step at the time of writing to add the screw in https://blot.hackclub.dev/assembly, despite having an instruction to put the nut in the trap for the screw:
<img width="605" alt="Screenshot 2024-01-19 at 15 38 44" src="https://github.com/hackclub/blot/assets/5891442/6565c925-06ab-4062-948e-bf4e9345e5a5">

**Comment by leomcelroy** [comment]
This screw is actually supposed to be tightened by hand. That screw could be better though, shorter and with knurling perhaps.

**Comment by maxwofford** [comment]
@leomcelroy the screw I found in the kit was too hard to first-time tighten by hand due to https://github.com/hackclub/blot/issues/248 on the tool head. This should either be pre-threaded by screwing it in at the office, or a tool for tightening be provided.

**Comment by leomcelroy** [comment]
This is addressed in the new bom.

https://github.com/hackclub/blot/blob/main/docs/BOM.toml
