### ISSUE TITLE
Instructions out of order

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#244]
I just went through and built a blot from one of the demo kits in the office.

There's an instruction to add a nut to a nut trap in the Printed Rail component:
<img width="876" alt="Screenshot 2024-01-19 at 15 40 29" src="https://github.com/hackclub/blot/assets/5891442/c91be0f7-799c-485d-96ee-f517eb6215f3">

The nut isn't referenced again until Final Assembly, 2 chapters later:
<img width="1058" alt="Screenshot 2024-01-19 at 15 41 20" src="https://github.com/hackclub/blot/assets/5891442/3a42da53-047f-4021-b789-e3736f59403c">

In between the steps, the nut fell out of the trap multiple times:
![IMG_0748](https://github.com/hackclub/blot/assets/5891442/8195506b-a18a-4ae9-9b7a-3060e6a280fc)
![IMG_0747](https://github.com/hackclub/blot/assets/5891442/e749f9b5-b42c-42d7-97cd-3f27c475cd32)

I'd suggest adding the nut trap, and adding the belt bearing assembly in the Printed Rail component chapter, then only needing to add the belt during final assembly.

**Comment by leomcelroy** [comment]
I agree with reordering this.

**Comment by leomcelroy** [comment]
Corrected on new assembly guide.
