### ISSUE TITLE
Using smaller screws on the toolhead v-wheels

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#245]
I just went through and built a blot from one of the demo kits in the office.

![IMG_0742](https://github.com/hackclub/blot/assets/5891442/ea971257-1056-40b7-b4ea-522eecc6dea0)

The instructions use an m5x35 screw for the toolhead, but they stick out of the toolhead by quite a bit. I was wondering if should swap that with an m5x20 or smaller?

**Comment by leomcelroy** [comment]
We wanted to reduce the part count. Open to adding a screw to make it fit better though. Think we actually had decided on doing so in the past.
