### ISSUE TITLE
Stepper motors at office are too tall

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#246]
I just went through and built a blot from one of the demo kits in the office.

The stepper motors we have are too tall for the blot's legs and the machine rests on it's motors
![IMG_0736](https://github.com/hackclub/blot/assets/5891442/d43f4409-9eb7-433d-a45d-fb2449cea9d2)

**Comment by leomcelroy** [comment]
These are just the wrong motors. Will fix in future by getting the right ones.
