### ISSUE TITLE
Stepper motors lack headers

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#247]
I just went through and built a blot from one of the demo kits in the office.

The stepper motors are 4-cable steppers that terminate in a split-end wire thread. The board's pinout for the stepper motor drivers is a 4 pin male header. I didn't get a soldering iron in the assembly kit, and without my own soldering kit I won't be able to wire up the stepper motors

**Comment by leomcelroy** [comment]
Definitely we don't have the right motors at the office. I'll lock this down and find a sustainable source.
