### ISSUE TITLE
Toolhead nut trap tolerances too tight

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#248]
I just went through and built a blot from one of the demo kits in the office.

While I assembled it I found the nut traps on the toolhead too tight for the nuts until I drilled them out by screwing through them to sink the nut.

![IMG_0739](https://github.com/hackclub/blot/assets/5891442/d79ceeaf-de2d-462c-ad51-3f901853ab77)

This is totally fine by itself, but the instructions asked me to sink nut traps on opposite sides of the part, which meant that gravity wouldn't let the nuts stay in their area. I'd prefer to assemble the bearing assemblies first, then sink the nut second, then flip the part over 3rd so I can do the other side.

<img width="384" alt="Screenshot 2024-01-19 at 15 50 13" src="https://github.com/hackclub/blot/assets/5891442/e5b148e4-4fcc-40e0-a391-7fa5fc4b028e">

**Comment by BrightTheBackpack** [comment]
Same issue happened here, I just screwed it jn with the nut outside of the nut trap

**Comment by leomcelroy** [comment]
This should change with our new part suppliers. Will re-evaluate when we receive test kits.
