### ISSUE TITLE
Document how to re-align V-wheel

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#249]
﻿I just went through and built a blot from one of the demo kits in the office.

One of the part boxes contained a v-wheel with a dislocated washer through the middle:
![IMG_0740](https://github.com/hackclub/blot/assets/5891442/0d764b95-9bae-492b-a27d-121435d02bf7)

This ended up being an easy fix to grab another v-wheel, but I want to flag this issue in case we want more of a process around q/a for shipping parts.

**Comment by leomcelroy** [comment]
This isn't broken. You just need to recenter the washer. I take an allen and swirl it around the hole.

**Comment by maxwofford** [comment]
Marking this as won't fix then, as it sounds like the underlying issue isn't as big as originally thought.

**Comment by BrightTheBackpack** [comment]
Should i add this to tuning.md or assesmbly.,md?

**Comment by maxwofford** [comment]
Assembly guide @BrightTheBackpack, because we encounter it while assembling!
