### ISSUE TITLE
add mounting for control board

### ISSUE THREAD

**Issue by karamassie** [hackclub/blot#25]

**Comment by Sheepy3** [comment]
first test-ready version done, waiting new pcb's to iterate

**Comment by Sheepy3** [comment]
waiting on new-new pcb's to arrive to create new version with new mountain for blot v4

**Comment by Sheepy3** [comment]
board mounting mechanism designed, designing rail mounting design

**Comment by Sheepy3** [comment]
designed initial iteration of pcb mount, refining. Will push a version on monday

**Comment by Sheepy3** [comment]
uploading a version of the pcb mount
