### ISSUE TITLE
How do I flash the blot firmware

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#251]
I just got through the guide on https://blot.hackclub.dev/assembly and plugged my blot into my computer but it doesn't follow the controls on the editor. I'm assuming I need to flash it with something, but there aren't any instructions to in the guide

**Comment by BrightTheBackpack** [comment]
https://github.com/hackclub/blot/blob/main/hardware/motor-control-board/SETUP.md 
I'm assuming it's not in assembly because it's supposed to be flashed before it's shipped(I'm assuming you've already found this, close the issue?)

**Comment by maxwofford** [comment]
Yep! Closing this now because it's documented in the packing guide
