### ISSUE TITLE
No position function outwards facing

### ISSUE THREAD

**Issue by evan-gan** [hackclub/blot#265]
Could we add an outwards facing position function to blot? Currently there is nothing that does this to my knowledge, and the position is already stored in the class. This should only take a few lines of code. 
I believe the function below could be added to [`virtual-gallery/drawing-functions/Turtle.js`](https://github.com/hackclub/blot/blob/main/virtual-gallery/drawing-functions/Turtle.js) to implement this functionality.
```javascript
pos() {
    return this.location
  }
```

**Comment by BrightTheBackpack** [comment]
I believe it should be added to astro/src/lib/drawingToolkit
/turtle.ts, not the virtual gallery one

**Comment by maxwofford** [comment]
This is a great idea though! I was hoping to have it a couple of times while working on my art.

**Comment by BrightTheBackpack** [comment]
also i think t.end sort of does this?

**Comment by maxwofford** [comment]
@BrightTheBackpack that's a little confusing. Should this be an alias of that function or does it do something else?

**Comment by evan-gan** [comment]
If it a method returned `this.location` from the turtles internals that should be better, because it would work if the turtle had not path. (I believe t.end only works when a path has been made)
