### ISSUE TITLE
Make blot logo in tab black

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/blot#270]
It's not visible right now when the tab is selected.

![Screenshot 2024-02-01 at 9 54 16 AM](https://github.com/hackclub/blot/assets/27078897/732bd2ad-79c1-4a1b-a397-bd625aeb3ea2)

![Screenshot 2024-02-01 at 9 54 09 AM](https://github.com/hackclub/blot/assets/27078897/ba9f2949-9643-40bc-9f29-3143a108b1d1)

**Comment by shyakachaste** [comment]
Hello @leomcelroy , iam chaste , iam also the member of hack club , may you please give me more information about that issue, thanks

**Comment by shyakachaste** [comment]
![borpheus](https://github.com/hackclub/blot/assets/121980393/c2ccbd66-6b9c-449a-a926-2a23cb5ae790)
i have changed that shortcut icom, iam waiting hack club to merge the pull request
