### ISSUE TITLE
Manual control

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#315]
[Context in slack](https://hackclub.slack.com/archives/C04GCH8A91D/p1708638801070669?thread_ts=1708637885.496789&cid=C04GCH8A91D)

Here's an example of how octoprint's UI looks:
<img width="487" alt="Screenshot 2024-02-22 at 18 00 44" src="https://github.com/hackclub/blot/assets/5891442/cbfa5c99-2254-4889-bf87-7033d7c444ab">

**Comment by leomcelroy** [comment]
This is a dupe of #91
