### ISSUE TITLE
Is there a file that lists the methods of blot?

### ISSUE THREAD

**Issue by FOSSBOSS** [hackclub/blot#413]
I see const t = new bt.Turtle();
which leads me to believe this is a js implementation of turtle. OK,  cool. so  I tried some methods like penup() pendown() circle(n)
all of which failed. So I went to read more about the implementation of blots version of turtle, but have yet to find the documentation. 
 
 To be more specific, I do mean an online reference, something akin to:
 https://docs.python.org/3/library/turtle.html
 
 I did find the turtle implementation in the source code. penup() and pendown() are up(),  down() 
 I did not see implementations for shapes. Maybe I should write those.
 
 Anyway, I think an online reference would be nice. 
 Alternatively, if the methods more closely matched the Turtle methods,  you could probably just use the python documentation.

**Comment by BrightTheBackpack** [comment]
https://blot.hackclub.com/docs

**Comment by FOSSBOSS** [comment]
Very good, thanks!

**Comment by BrightTheBackpack** [comment]
Can you close this?
