### ISSUE TITLE
clean up CAD model

### ISSUE THREAD

**Issue by karamassie** [hackclub/blot#44]
- improved PCB mount and shoes (please work with @Sheepy3  )

**Comment by Sheepy3** [comment]
testing assembly of v3 parts today. will see if theres anything that can be optimized. in terms of printability, @Merlin04 has already done an excellent job with their additions. design cohesivity (consistency of curves vs sharp edges etc) may need another pass, would love help with that

**Comment by Sheepy3** [comment]
did pass on design cohesivity for pen holder, printed rail + motor holders probably need some curves on the edges
