### ISSUE TITLE
Missing, which one should 3D print and which one machine milled(Metal). 

### ISSUE THREAD

**Issue by salmanfarisvp** [hackclub/blot#477]
Hi, Do we have a document about which part is 3D printed and which part is machined?

**Comment by leomcelroy** [comment]
Thanks for inquiring this could be better documented. It's all described in the BOM.toml

https://github.com/hackclub/blot/blob/main/docs/BOM.toml

**Comment by leomcelroy** [comment]
The only metal part is the plate on the carriage. It could also be printed in theory but better to be metal if possible.
