### ISSUE TITLE
Missing Timing Belt details on BOM

### ISSUE THREAD

**Issue by salmanfarisvp** [hackclub/blot#494]
Hi, I see the timing belt details are missing in the BOM. Is it possible to share the timing belt details? Is that GT2 Timing belt and pulleys

**Comment by BrightTheBackpack** [comment]
It's already in the BOM. it seems like this one: https://openbuildspartstore.com/gt2-2m-timing-belt-by-the-foot/
you can find it by going to the BOM, and ctrl+f timing belt

**Comment by leomcelroy** [comment]
It is yes! I think this is corrected in the new BOM.
