### ISSUE TITLE
[software/firmware] sequential motor control

### ISSUE THREAD

**Issue by exu3** [hackclub/blot#6]
We need smoother motion for our machine. Right now we stop at each corner; it would be better to interpolate between them.

https://github.com/modular-things/modular-things/blob/main/src/lib/virtualThings/synchronizer.js

**Comment by leomcelroy** [comment]
The current code for the firmware is here: https://github.com/hackclub/haxidraw/blob/main/motor-control-board/firmware/firmware.ino
