### ISSUE TITLE
Share link broken when shared from guide

### ISSUE THREAD

**Issue by BrightTheBackpack** [hackclub/blot#603]
When you create a share link while on a guide, the share link won't work. 
Fixes:
1.  make it so all share links don't have the guide paramater in the URL
2. make it so even if it does have a guide parameter, it will still load the shared code

fix 1 is easy so i'm going to try and figure out fix 2 in the meantime

**Comment by leomcelroy** [comment]
Thanks so much for pointing this out. I think the issue was it was assuming there were no url params when creating the share link. I strip them all out now with commit `dc8d82a0 `.
