### ISSUE TITLE
create shipping procedure

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/blot#68]
- how to package machines
- need to buy boxes

**Comment by Sheepy3** [comment]
ordered sample filament, sample wheels

**Comment by Sheepy3** [comment]
sample package arrived, but I am not positive on this box being the best for the machine. I'm going to look into more samples before I go home for the day, but will come to a decision soon as we near the end of october.

**Comment by Sheepy3** [comment]
ordered 100x boxes whiich are a lot nicer than the one tested in september
