### ISSUE TITLE
GH Action: PRs for new art should automatically link "Preview in editor"

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#691]
automatically posts a “preview in editor” link on each PR which updates when files are changed (ie. like in this PR https://github.com/hackclub/blot/pull/657) should have a link to `https://blot.hackclub.com/editor?src=https://raw.githubusercontent.com/zFa3/blot/b28fbbec865ec3a8922843cc81e3074c1f1d261e/art/Royal-Jayden/index.js`

**Comment by Aryankpoor** [comment]
**Hello, I saw help was needed for this issue in slack and I asked if I could work on it .** 
Before I work on the solution, I wanted to ask , do you want the link to lead to the added file in the PR or the link that they provided for the code?

**Comment by maxwofford** [comment]
@Aryankpoor I want to preview their art. Currently, I need to copy the code from their index.js file, go to https://blot.hackclub.com/editor, then paste that in. Instead I want a link to show up that says "Try this art out in the editor" in the PR and I can click that to get their code prefilled

**Comment by Aryankpoor** [comment]
A simple solution would be by pressing . (dot button) which would open up codespaces. Which would open a vscode environment in the browser where you can simply click run and it will run the code

**Comment by Aryankpoor** [comment]
No need to add github actions at all

**Comment by maxwofford** [comment]
That's not what I'm looking for! Have you tried clicking the links in https://github.com/hackclub/blot/issues/691#issue-2406990193 to see what I mean?

**Comment by Aryankpoor** [comment]
I have provided the solution on slack please check
