### ISSUE TITLE
New preview github action shows error

### ISSUE THREAD

**Issue by Aryankpoor** [hackclub/blot#722]
The new preview github action for pull requests shows error. A sample of this error can be observed by visiting the preview your blot link in #721 . The error has also been shown in the image below 
![image](https://github.com/user-attachments/assets/43c20e02-e004-401f-b81f-092f61f586f5)

**Comment by BrightTheBackpack** [comment]
this happened cause there was a space in the directory, which isn't allowed per 2.2 of the submission rules https://github.com/hackclub/blot/blob/main/docs/GET_A_BLOT.md

**Comment by Aryankpoor** [comment]
Closing this as solved.
