### ISSUE TITLE
Blot draws programs from blot JS programs backwards but SVG imports are correctly mirrored

### ISSUE THREAD

**Issue by whatwareweb** [hackclub/blot#737]
When printing any program on the Blot from a JS program in the editor, it comes out reversed like shown in the pictures:

web preview:
![image](https://github.com/user-attachments/assets/9a297432-bdcd-4305-8310-634330573137)

actual blot printout:
![2024-07-24-09-22-12-324](https://github.com/user-attachments/assets/9c29ee20-2aa5-4bc4-a55d-9f57c1df471d)

If you look at the bottom of the pictures you can see the little R symbol there has been reversed.

This issue can be fixed by reversing which wires are plugged into which stepper motor on the real blot. However, when you import an SVG to print, then the SVG is imported backwards. I cannot tell why this was done or whether this was to compensate for this issue or not, but this behavior makes it necessary to keep swapping the stepper motor wires.

The solutions for this issue include

- adding in the blot instructions to swap the stepper motor wires, and do not mirror the image when an SVG is imported
- compensate for the mirroring of the printing in software, such as the JS that sends the commands to the Blot, then do not mirror the SVG import
- Mirror everything in the preview so that users will have an accurate representation of the printout (will break some existing programs)

**Comment by BrightTheBackpack** [comment]
we already have instructions on swapping the stepper motor wires in our assembly doc

> The machine will work with any configuration of how the stepper motor pins are plugged in. Depending on how your stepper motors are plugged in the drawing may be mirrored. You can correct this by changing whether the motors are plugged in with the metal pins showing face up or hidden face down. The correct orientation may be some combination of the two. I'll note this again when we cover setting the machine origin.

**Comment by BrightTheBackpack** [comment]
I believe svgs are a separate problem, due to the fact that an svg's normal coordinate system goes from top to down, but our coordinate system goes from bottom up

**Comment by whatwareweb** [comment]
OK i will look into it then. i will probably PR soon
