### ISSUE TITLE
add missing parts to machine sim

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/blot#77]
- screws
- gears
- belt
- pen
- servo

**Comment by leomcelroy** [comment]
@Sheepy3 can you provide us with these models so we can add them to the website

**Comment by Sheepy3** [comment]
repairing assembly in onshape. so far:

-updated carriage with eccentric spacers
-added missing screws to upper rail 
-updated pen holder with eccentric spacer

**Comment by Sheepy3** [comment]
no longer using machine sim?
