### ISSUE TITLE
run machine 100 hours

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/blot#94]
Make one in petg. Run it for a long time making lots of art. Report on what happens.

**Comment by Sheepy3** [comment]
machine made in prusament petg, awaiting board from Hugo in order to test. when spool from printerior arrives, will produce a new blot in their filament and test that as much as possible. will likely need a dedicated computer connected for this purpose

**Comment by Sheepy3** [comment]
started running tests on machine today!

**Comment by Sheepy3** [comment]
machine has run at least 150 hours, with minimal wear. will continue to test past this
