### ISSUE TITLE
Fix blot documentation

### ISSUE THREAD

**Issue by TuinboonDev** [hackclub/blot#994]
Some functions like: translate, rotate and scale dont work in the online editor. There are some inconsistencies aswell, `new bt.Turtle()` is the correct way to create a turtle but in the [TOOLKIT ](https://github.com/hackclub/blot/blob/main/docs/TOOLKIT-v0.1.0.md) it says `const t = createTurtle()`

**Comment by BrightTheBackpack** [comment]
That's the toolkit from version 0.1.0. The current documeIntation can be found in [DOCUMENTATION.MD](https://github.com/hackclub/blot/blob/main/docs/DOCUMENTATION.md)MD. AFAIK the website uses the new docs.
